
package helloservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import java.lang.annotation.Inherited;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 */
@WebService(targetNamespace = "http://endpoint.helloservice/", serviceName = "HelloService", name = "HelloPortType", portName = "HelloPort")
public interface Hello {

    /**
     * @param name
     * @return returns java.lang.String
     */
//    @WebMethod
    public String sayHello(/*@WebParam*/ String name);

}
